name="shunting-yard-fortran"
version="0.0.3"
license="MIT"
author="Ian Giestas Pauli"
maintainer = "iangiestas@usp.br"
copyright = "2020 Ian Giestas Pauli"

[ library ]
include-dir = "include"

[ dependencies ]
fortran-tokenizer = { git = "https://github.com/14NGiestas/fortran-tokenizer.git", tag="v0.1.1"}
